/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Datos;


import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kacper Borylo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        iniciarModelos();
    }
    
    private void iniciarModelos(){
        modeloMadrid = new DefaultComboBoxModel();
        modeloBarcelona = new DefaultComboBoxModel();
        modeloBarcelona.addElement("Marc-André ter Stegen");
        modeloBarcelona.addElement("Neto Murara");
        modeloBarcelona.addElement("Óscar Mingueza");
        modeloBarcelona.addElement("Gerard Pique");
        modeloBarcelona.addElement("Ronald Araujo");
        modeloBarcelona.addElement("Sergiño Dest");
        modeloBarcelona.addElement("Frenkie de Jong");
        modeloBarcelona.addElement("Riqui Puig");
        modeloBarcelona.addElement("Miralem Pjanic");
        modeloBarcelona.addElement("Lionel Messi");
        modeloBarcelona.addElement("Antoine Griezzmann");
        modeloBarcelona.addElement("Ousmane Dembelé");
        modeloBarcelona.addElement("Pedri");
        modeloBarcelona.addElement("Martin Braithwaite");
        modeloMadrid.addElement("Thibaut Courtois");
        modeloMadrid.addElement("Andriy Lunin");
        modeloMadrid.addElement("Sergio Ramos");
        modeloMadrid.addElement("Raphael Varane");
        modeloMadrid.addElement("Ferland Mendy");
        modeloMadrid.addElement("Marcelo Vieira");
        modeloMadrid.addElement("Toni Kroos");
        modeloMadrid.addElement("Luka Modric");
        modeloMadrid.addElement("Casemiro");
        modeloMadrid.addElement("Isco Alarcon");
        modeloMadrid.addElement("Karim Benzema");
        modeloMadrid.addElement("Marco Asensio");
        modeloMadrid.addElement("Vinicius Junior");
        modeloMadrid.addElement("Eden Hazard");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMandar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxEquipo = new javax.swing.JComboBox<>();
        jComboBoxJugadores = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMandar.setText("Mandar a la Nube");
        jButtonMandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMandarActionPerformed(evt);
            }
        });

        jLabel1.setText("            FC BARCELONA O REAL MADRID");

        jComboBoxEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo", "Barcelona", "Real Madrid" }));
        jComboBoxEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEquipoActionPerformed(evt);
            }
        });

        jComboBoxJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugadores" }));

        jTextField1.setText("Escoje tu equipo de Futbol Favorito");

        jTextField2.setText("Escoje a tu jugador Favorito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jComboBoxJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jComboBoxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonMandar)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonMandar)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jComboBoxEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEquipoActionPerformed
        // TODO add your handling code here:
        
        int opc;
        
        opc = jComboBoxEquipo.getSelectedIndex();
        
        switch(opc){
            case 0:
                JOptionPane.showMessageDialog(rootPane,"Selecciona un equipo","",2);
                break;
            case 1:
                jComboBoxJugadores.setModel(modeloBarcelona);
                break;
            case 2:
                jComboBoxJugadores.setModel(modeloMadrid);
                break;
            
        }
        
    
    }//GEN-LAST:event_jComboBoxEquipoActionPerformed

    private void jButtonMandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMandarActionPerformed
        // TODO add your handling code here:
         Nube ventana = new Nube();
        
         
        ventana.equipo = (String) jComboBoxEquipo.getSelectedItem();
        ventana.jugador = (String) jComboBoxJugadores.getSelectedItem();
        
       
            
        
        
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMandarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    private javax.swing.DefaultComboBoxModel<String> modeloMadrid;
    private javax.swing.DefaultComboBoxModel<String> modeloBarcelona;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMandar;
    private javax.swing.JComboBox<String> jComboBoxEquipo;
    private javax.swing.JComboBox<String> jComboBoxJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
